hw_10/hw_10/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

hw_10/quotes/urls.py
#from django.contrib import admin
from django.urls import path
from . import views

app_name = 'quotes'
urlpatterns = [
    path('', views.main, name='root'),
    path('<int:page>', views.main, name='root_paginate'),
    path("author/<str:fullname>/", views.author, name="author"),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    #path('admin/', views.main, name='root'),
]

hw_10/users/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from . import views
from .forms import LoginForm, RegisterForm

app_name = 'users'

urlpatterns =[
    path('signup/', views.RegisterView.as_view(template_name='users/register.html', form_class=RegisterForm), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html', form_class=LoginForm), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout')
    ]

hw_10/quotes/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Author(models.Model):
    fullname = models. CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models. TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)

class Quote (models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

"""from django.db import models
from django.contrib.auth.models import User

class Author(models.Model):
    name = models.CharField(max_length=100)
    bio = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name"""

hw_10/users/models.py
from django.db import models

# Create your models here.

hw_10/quotes/forms.py
from django import forms
from .models import Author, Quote

class AuthorForm(forms.ModelForm):
    fullname = forms.CharField(max_length=50, required=True)
    born_date = forms.CharField(max_length=50)
    born_location = forms.CharField(max_length=50)
    description = forms.Textarea

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

class QuoteForm(forms.ModelForm):
    quote = forms.Textarea
    author = forms.CharField(max_length=50, required=True)

    class Meta:
        model = Quote
        fields = ['quote', 'author']
        exclude = ['tags']

hw_10/users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django. forms import ModelForm, CharField, TextInput, EmailField, EmailInput, PasswordInput

class RegisterForm(UserCreationForm):

    username = CharField(max_length=16,
                         min_length=3,
                         required=True,
                         widget=TextInput(attrs={"class": "form-control"}))

    email = EmailField(max_length=50,
                       required=True,
                       widget=EmailInput(attrs={"class": "form-control"}))

    password1 = CharField(required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))

    password2 = CharField(required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class LoginForm(AuthenticationForm):

    username = CharField(max_length=16,
                         min_length=3,
                         required=True,
                         widget=TextInput(attrs={"class": "form-control"}))

    password = CharField(required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ['username', 'password']

hw_10/quotes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Author, Tag, Quote
from .utils import get_mongodb
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .forms import AuthorForm

# Create your views here.

def main(request, page=1):
    quotes = Quote.objects.order_by('-created_at').all()
    per_page = 10
    paginator = Paginator(quotes, per_page)
    quotes_on_page = paginator.page(page)
    return render(request, "quotes/index.html", context={'quotes': quotes_on_page})

def author(request, fullname):
    author = get_object_or_404(Author, fullname=fullname)
    born_date = author.born_date[:11]
    return render(request, 'quotes/author.html', context={'author': author,
                                                               'born_date_formatted': born_date})
@login_required
def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect(to='quotes:root')
    return render(request, 'quotes/add_author.html', context={'form': AuthorForm()})

@login_required
def add_quote(request):
    if request.method == "POST":
        raw_tags = request.POST.get('tags')
        tags = []
        for t in raw_tags.split(','):
            tag, _ = Tag.objects.get_or_create(name=t.strip())
            tags.append(tag)
        author_name = request.POST.get('author')
        author, _ = Author.objects.get_or_create(fullname=author_name.strip())
        quote_text = request.POST.get('quote')
        quote = Quote.objects.create(quote=quote_text, author=author)
        quote.tags.set(tags)
        return redirect(to='quotes:root')
    return render(request, 'quotes/add_quote.html')

"""@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main')
    else:
        form = AuthorForm()
    return render(request, 'quotes/add_author.html', {'form': form})"""

hw_10/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from .forms import RegisterForm

# Create your views here.

class RegisterView(View):
    template_name = 'users/register.html'
    form_class = RegisterForm

    def get(self, request):
        return render(request, self.template_name, context={'form': self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request, message=f'Hello {username}!. Your account register successfully!')
            return redirect(to='users:login')
        return render(request, self.template_name, context={'form': form})

hw_10/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}

{% load static %}

<div>
    <h2>Add new author</h2>
</div>

<form action="{% url 'quotes:add_author' %}" method="post">
    {% csrf_token %}
    <div class="row" bis_skin_checked="1">
        <div class="form-group col-xs-3" bis_skin_checked="1">
            <label for="id_fullname">Author`s name:</label>
            <input type="text" class="form-control" id="id_fullname" name="fullname">
        </div>
    </div>

    <div class="row" bis_skin_checked="1">
        <div class="form-group col-xs-3" bis_skin_checked="1">
            <label for="id_born_date">Date of birth:</label>
            <input type="text" class="form-control" id="id_born_date" name="born_date">
        </div>
    </div>

    <div class="row" bis_skin_checked="1">
        <div class="form-group col-xs-3" bis_skin_checked="1">
            <label for="id_born_location">City of birth:</label>
            <input type="text" class="form-control" id="id_born_location" name="born_location">
        </div>
    </div>

    <div class="row" bis_skin_checked="1">
        <div class="form-group col-xs-3" bis_skin_checked="1">
            <label for="id_description">Description:</label>
            <textarea class="form-control" id="id_description" name="description"></textarea>
        </div>
    </div>

    <input type="submit" value="Add" class="btn btn-primary">

</form>

{% endblock %}

hw_10/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'quotes/bootstrap.min.css'%}">

<div>
    <h2>Add new quote</h2>
</div>

<form action="{% url 'quotes:add_quote' %}" method="post">
    {% csrf_token %}
    <div class="row" bis_skin_checked="1">
        <div class="form-group col-xs-3" bis_skin_checked="1">
            <label for="id_author">Author`s name:</label>
            <input type="text" class="form-control" id="id_author" name="author">
        </div>
    </div>

    <div class="row" bis_skin_checked="1">
        <div class="form-group col-xs-3" bis_skin_checked="1">
            <label for="id_text">Quote:</label>
            <textarea class="form-control" id="id_text" name="quote"></textarea>
        </div>
    </div>

    <div class="row" bis_skin_checked="1">
        <div class="form-group col-xs-3" bis_skin_checked="1">
            <label for="id_tags">Tags:</label>
            <input type="text" class="form-control" id="id_tags" name="tags">
            # enter your tags separated with ','
        </div>
    </div>

    <input type="submit" value="Add" class="btn btn-primary">

</form>

{% endblock %}

hw_10/quotes/templates/quotes/author.html
{% extends 'quotes/base.html' %}

{% block content %}

{% load static %}

<div class="author-details" bis_skin_checked="1">
    <h3 class="author-title">{{author.fullname}}</h3>
</div>

<div class="form-group col-xs-3" bis_skin_checked="1">
    <label>Born:</label>
    <span class="author-born-date">{{born_date_formatted}}</span>
    <span class="author-born-location">{{author.born_location}}</span>
</div>

<div>
    <label>Description:</label>
    <span class="author-description" bis_skin_checked="1">{{author.description}}</span>
</div>

</div>

{% endblock %}

hw_10/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Homework</title>
</head>
<body>

    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    {% if user.is_authenticated %}
                    <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary">Add quote</a>
                    <a href="{% url 'quotes:add_author' %}" class="btn btn-primary">Add author</a>
                    <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>

                    {% else %}
                    <a href="{% url 'users:signup' %}" class="btn btn-primary">SignUp</a>
                    <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                    {% endif %}

                </p>
            </div>
        </div>


    {% block content %} {% endblock %}

    </div>
    <footer class="footer">
        <div class="container">

        </div>
    </footer>


</body>
</html>

hw_10/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<div class="row">
    <div class="col-md-8">
    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">
            {{quote.quote}}
        </span>
        <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="/author/{{quote.author.fullname}}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags.all %}
            <a class="tag" href="/tag/{{tag}}">{{tag.name}}</a>
            {% endfor %}
        </div>
    </div>

    {% endfor %}
    <nav>

        <ul class="pager">

            <li class="previous">
                <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                        href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous</a>
            </li>


            <li class="next">
                <a class="{% if not quotes.has_next %} disabled {% endif %}"
                        href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">Next <span aria-hidden="true">→</span></a>
            </li>

        </ul>

    </nav>
    </div>

</div>

{% endblock %}

hw_10/users/templates/users/login.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Login User</h2>

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <span {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</span>
        {% endfor %}
    </div>
    {% endif %}

    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>

        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password }}
            </label>
            <span>{{form.errors.password}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

hw_10/users/templates/users/logout.html
{% extends 'quotes/base.html' %}

{% block content %}

    <div class="container mt-3">
        <h1>Return please!</h1>
    </div>

{% endblock %}

hw_10/users/templates/users/register.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Register User</h2>
    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Email
                {{ form.email }}
            </label>
            <span>{{form.errors.email}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password1 }}
            </label>
            <span>{{form.errors.password1}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Repeat Password
                {{ form.password2 }}
            </label>
            <span>{{form.errors.password2}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}